repos:
    - repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
          - id: black
            args: ['--line-length', '92', '--target-version', 'py312']

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-ast
          - id: sort-simple-yaml

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.11.0
      hooks:
          - id: pyupgrade
            args: [--py311-plus]

    - repo: https://github.com/tox-dev/pyproject-fmt
      rev: '1.1.0'
      hooks:
          - id: pyproject-fmt

    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: 'v0.0.290'
      hooks:
          - id: ruff
            args: ['--fix', '--respect-gitignore']
