on: [push]

env:
    PYTHONFORANDROID_PREREQUISITES_INSTALL_INTERACTIVE: 0

name: Android
jobs:
    Integration:
        strategy:
            matrix:
                python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
                os:
                    - 'ubuntu-latest'

        runs-on: ${{ matrix.os }}
        steps:
            - name: Setup python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Poetry
              run: |
                  pip install poetry
                  poetry install
                  poetry shell

            - run: buildozer --help
            - name: Install Linux dependencies
              run: sudo apt -y install automake
            - name: buildozer android debug
              run: buildozer android debug
