name: Python package

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.8', '3.9', '3.10', '3.11']

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - uses: actions/checkout@v3
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true
            - name: Install dependency
              run: |
                  poetry install --sync --no-interaction --no-root
            - name: Test with pytest
              run: |
                  pytest .
